#!/usr/bin/env bash

# Needs a file database at $HOME/.cache/rofi_file_db, which has a file name
# in each line. This can be grepped through the 'locate' command.
# A sample updatedb script, which calls the real updatedb command and filters
# files according to $HOME/.config/rofi/locate_ignore is also provided.
# locate_ignore file should also include a string to be `grep -v'ed in each line

# Handle argument.
if [[ -s $HOME/.cache/rofi_file_db ]]; then
  if [ -n "$@" ]; then
    FILE="$@"
  fi

  if [[ -f $FILE ]]; then
    coproc ( xdg-open "$FILE"  >/dev/null 2>&1 )
    exec 1>&-
    exit;
  fi

  cat $HOME/.cache/rofi_file_db
else
  echo "Generate a file db first"
fi
