#!/bin/bash

sudo updatedb

filter () {
  awk '{ print length, $0 }' | sort -n -s | cut -d' ' -f2|cut -c$((${#HOME}+2))-
}

if [[ -s $HOME/.config/rofi/locate_ignore ]]; then
  ignore="$(cat $HOME/.config/rofi/locate_ignore|command sed 's/ /\|/g')"
  locate $HOME|grep -v "$ignore"|filter > $HOME/.cache/rofi_file_db
else
  locate $HOME|grep -v "$ignore"|filter > $HOME/.cache/rofi_file_db
fi
